name: app_show_categories
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  passcode_screen: ^2.0.1
  provider: ^6.1.1
  flutter_bloc: ^8.1.3
  dio: ^5.3.4
  either_dart: ^1.0.0
  get_it: ^7.6.4
  intl: 0.18.0
  flutter_slidable: ^3.0.1
  collection: ^1.17.1
  local_session_timeout: ^2.3.2
  rxdart: ^0.27.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  fonts:
    - family: DB Heavent
      fonts:
        - asset: lib/assets/font/DB Heavent Bd It v3.2.ttf
        - asset: lib/assets/font/DB Heavent Bd v3.2.ttf
        - asset: lib/assets/font/DB Heavent Blk It v3.2.ttf
        - asset: lib/assets/font/DB Heavent Blk v3.2.ttf
        - asset: lib/assets/font/DB Heavent It v3.2.ttf
        - asset: lib/assets/font/DB Heavent Li It v3.2.ttf
        - asset: lib/assets/font/DB Heavent Li v3.2.ttf
        - asset: lib/assets/font/DB Heavent Med v3.2.ttf
        - asset: lib/assets/font/DB Heavent Thin It v3.2.ttf
        - asset: lib/assets/font/DB Heavent Thin v3.2.ttf
        - asset: lib/assets/font/DB Heavent UlLi It v3.2.ttf
        - asset: lib/assets/font/DB Heavent UlLi v3.2.ttf
        - asset: lib/assets/font/DB Heavent v3.2.ttf

